In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
main_data = pd.read_csv("/content/battery_vs_gaming_dataset_medium.csv",delimiter=',')

In [ ]:
main_data.tail()

,Game_Name,Device_Type,Session_Time_Minutes,FPS,Battery_Start_%,Battery_End_%,Battery_Drop_%
995,Asphalt 9,iOS,10,30,90,62,28
996,Call of Duty,Android,143,90,79,52,27
997,BGMI,iOS,69,45,89,64,25
998,Free Fire,iOS,81,90,59,39,20
999,Free Fire,Android,160,45,31,9,22

In [ ]:
print(main_data['Game_Name'])

0         Free Fire
1         Asphalt 9
2         Free Fire
3      Call of Duty
4              BGMI
           ...
995       Asphalt 9
996    Call of Duty
997            BGMI
998       Free Fire
999       Free Fire
Name: Game_Name, Length: 1000, dtype: object

In [ ]:
main_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Game_Name             1000 non-null   object
 1   Device_Type           1000 non-null   object
 2   Session_Time_Minutes  1000 non-null   int64
 3   FPS                   1000 non-null   int64
 4   Battery_Start_%       1000 non-null   int64
 5   Battery_End_%         1000 non-null   int64
 6   Battery_Drop_%        1000 non-null   int64
dtypes: int64(5), object(2)
memory usage: 54.8+ KB

In [ ]:
main_data.describe()

,Session_Time_Minutes,FPS,Battery_Start_%,Battery_End_%,Battery_Drop_%
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.00000
mean,94.68900,69.285000,65.532000,42.947000,22.71100
std,50.79595,31.856375,20.590652,22.917841,10.23857
min,10.00000,30.000000,30.000000,0.000000,5.00000
25%,51.00000,45.000000,48.000000,25.000000,14.00000
50%,95.00000,60.000000,66.500000,43.000000,23.00000
75%,139.00000,90.000000,83.000000,61.000000,31.00000
max,180.00000,120.000000,100.000000,93.000000,40.00000

In [ ]:
main_data.tail()

,Game_Name,Device_Type,Session_Time_Minutes,FPS,Battery_Start_%,Battery_End_%,Battery_Drop_%
995,Asphalt 9,iOS,10,30,90,62,28
996,Call of Duty,Android,143,90,79,52,27
997,BGMI,iOS,69,45,89,64,25
998,Free Fire,iOS,81,90,59,39,20
999,Free Fire,Android,160,45,31,9,22

In [ ]:
a = main_data.loc[993,'Game_Name']
b = main_data.loc[885,'Game_Name']
c = main_data.loc[453,'Game_Name']
d = main_data.loc[345,'Game_Name']
e = main_data.loc[125,'Game_Name']
f = main_data.loc[75,'Game_Name']
g = main_data.loc[89,'Game_Name']
h = main_data.loc[129,'Game_Name']
i = main_data.loc[525,'Game_Name']
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)

Genshin Impact
Free Fire
Genshin Impact
Free Fire
BGMI
Free Fire
Genshin Impact
BGMI
BGMI

In [ ]:
# im performing isnull() function to find the nan in dataframe
main_data.isnull()

,Game_Name,Device_Type,Session_Time_Minutes,FPS,Battery_Start_%,Battery_End_%,Battery_Drop_%
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False

In [ ]:
# im performing the isnull fuction with sum beacause to find out the
main_data.isnull().sum()

Game_Name               0
Device_Type             0
Session_Time_Minutes    0
FPS                     0
Battery_Start_%         0
Battery_End_%           0
Battery_Drop_%          0
dtype: int64

In [ ]:
print(main_data)

        Game_Name Device_Type  Session_Time_Minutes  FPS  Battery_Start_%  \
0       Free Fire         iOS                    86   90               53
1       Asphalt 9     Android                    15   30               63
2       Free Fire         iOS                   164  120               80
3    Call of Duty     Android                    15   45               64
4            BGMI         iOS                   174   30               75
..            ...         ...                   ...  ...              ...
995     Asphalt 9         iOS                    10   30               90
996  Call of Duty     Android                   143   90               79
997          BGMI         iOS                    69   45               89
998     Free Fire         iOS                    81   90               59
999     Free Fire     Android                   160   45               31

     Battery_End_%  Battery_Drop_%
0               40              13
1               43              20
2               50              30
3               41              23
4               56              19
..             ...             ...
995             62              28
996             52              27
997             64              25
998             39              20
999              9              22

[1000 rows x 7 columns]

In [ ]:
d22 = pd.get_dummies(main_data['Device_Type'],dtype=int)
print(d22)

     Android  iOS
0          0    1
1          1    0
2          0    1
3          1    0
4          0    1
..       ...  ...
995        0    1
996        1    0
997        0    1
998        0    1
999        1    0

[1000 rows x 2 columns]

In [ ]:
pd.Categorical(main_data['Device_Type'])

['iOS', 'Android', 'iOS', 'Android', 'iOS', ..., 'iOS', 'Android', 'iOS', 'iOS', 'Android']
Length: 1000
Categories (2, object): ['Android', 'iOS']

In [ ]:
pd.Categorical(main_data['Game_Name'])

['Free Fire', 'Asphalt 9', 'Free Fire', 'Call of Duty', 'BGMI', ..., 'Asphalt 9', 'Call of Duty', 'BGMI', 'Free Fire', 'Free Fire']
Length: 1000
Categories (5, object): ['Asphalt 9', 'BGMI', 'Call of Duty', 'Free Fire', 'Genshin Impact']

In [ ]:
main_data.head()

,Game_Name,Device_Type,Session_Time_Minutes,FPS,Battery_Start_%,Battery_End_%,Battery_Drop_%
0,Free Fire,iOS,86,90,53,40,13
1,Asphalt 9,Android,15,30,63,43,20
2,Free Fire,iOS,164,120,80,50,30
3,Call of Duty,Android,15,45,64,41,23
4,BGMI,iOS,174,30,75,56,19

In [ ]:
main_data['Game_Name'].value_counts()

Game_Name
Genshin Impact    208
Free Fire         203
Asphalt 9         200
BGMI              198
Call of Duty      191
Name: count, dtype: int64